/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.amf.registration.sb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.docs.amf.registration.sb.model.AmfRegistration;
import com.liferay.docs.amf.registration.sb.model.AmfRegistrationModel;
import com.liferay.docs.amf.registration.sb.model.AmfRegistrationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AmfRegistration service. Represents a row in the &quot;AMF_AmfRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AmfRegistrationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AmfRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmfRegistrationImpl
 * @see AmfRegistration
 * @see AmfRegistrationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AmfRegistrationModelImpl extends BaseModelImpl<AmfRegistration>
	implements AmfRegistrationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a amf registration model instance should use the {@link AmfRegistration} interface instead.
	 */
	public static final String TABLE_NAME = "AMF_AmfRegistration";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dummy", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dummy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AMF_AmfRegistration (dummy LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table AMF_AmfRegistration";
	public static final String ORDER_BY_JPQL = " ORDER BY amfRegistration.dummy ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AMF_AmfRegistration.dummy ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.amf.registration.sb.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.docs.amf.registration.sb.model.AmfRegistration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.amf.registration.sb.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.docs.amf.registration.sb.model.AmfRegistration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AmfRegistration toModel(AmfRegistrationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AmfRegistration model = new AmfRegistrationImpl();

		model.setDummy(soapModel.getDummy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AmfRegistration> toModels(
		AmfRegistrationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AmfRegistration> models = new ArrayList<AmfRegistration>(soapModels.length);

		for (AmfRegistrationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.docs.amf.registration.sb.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.docs.amf.registration.sb.model.AmfRegistration"));

	public AmfRegistrationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dummy;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDummy(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dummy;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AmfRegistration.class;
	}

	@Override
	public String getModelClassName() {
		return AmfRegistration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dummy", getDummy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dummy = (Long)attributes.get("dummy");

		if (dummy != null) {
			setDummy(dummy);
		}
	}

	@JSON
	@Override
	public long getDummy() {
		return _dummy;
	}

	@Override
	public void setDummy(long dummy) {
		_dummy = dummy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AmfRegistration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AmfRegistration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AmfRegistration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AmfRegistrationImpl amfRegistrationImpl = new AmfRegistrationImpl();

		amfRegistrationImpl.setDummy(getDummy());

		amfRegistrationImpl.resetOriginalValues();

		return amfRegistrationImpl;
	}

	@Override
	public int compareTo(AmfRegistration amfRegistration) {
		long primaryKey = amfRegistration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AmfRegistration)) {
			return false;
		}

		AmfRegistration amfRegistration = (AmfRegistration)obj;

		long primaryKey = amfRegistration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AmfRegistration> toCacheModel() {
		AmfRegistrationCacheModel amfRegistrationCacheModel = new AmfRegistrationCacheModel();

		amfRegistrationCacheModel.dummy = getDummy();

		return amfRegistrationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{dummy=");
		sb.append(getDummy());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append("com.liferay.docs.amf.registration.sb.model.AmfRegistration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dummy</column-name><column-value><![CDATA[");
		sb.append(getDummy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AmfRegistration.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AmfRegistration.class
		};
	private long _dummy;
	private AmfRegistration _escapedModel;
}