/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.amf.registration.sb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AmfRegistration service. Represents a row in the &quot;AMF_AmfRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.amf.registration.sb.model.impl.AmfRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.amf.registration.sb.model.impl.AmfRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmfRegistration
 * @see com.liferay.docs.amf.registration.sb.model.impl.AmfRegistrationImpl
 * @see com.liferay.docs.amf.registration.sb.model.impl.AmfRegistrationModelImpl
 * @generated
 */
@ProviderType
public interface AmfRegistrationModel extends BaseModel<AmfRegistration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf registration model instance should use the {@link AmfRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this amf registration.
	 *
	 * @return the primary key of this amf registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf registration.
	 *
	 * @param primaryKey the primary key of this amf registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dummy of this amf registration.
	 *
	 * @return the dummy of this amf registration
	 */
	public long getDummy();

	/**
	 * Sets the dummy of this amf registration.
	 *
	 * @param dummy the dummy of this amf registration
	 */
	public void setDummy(long dummy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AmfRegistration amfRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AmfRegistration> toCacheModel();

	@Override
	public AmfRegistration toEscapedModel();

	@Override
	public AmfRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}