/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.amf.registration.sb.service.base;

import com.liferay.docs.amf.registration.sb.model.AmfRegistrationAuditLog;
import com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogService;
import com.liferay.docs.amf.registration.sb.service.persistence.AmfRegistrationAuditLogPersistence;
import com.liferay.docs.amf.registration.sb.service.persistence.AmfRegistrationFinder;
import com.liferay.docs.amf.registration.sb.service.persistence.AmfRegistrationPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the amf registration audit log remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.docs.amf.registration.sb.service.impl.AmfRegistrationAuditLogServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.docs.amf.registration.sb.service.impl.AmfRegistrationAuditLogServiceImpl
 * @see com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogServiceUtil
 * @generated
 */
public abstract class AmfRegistrationAuditLogServiceBaseImpl
	extends BaseServiceImpl implements AmfRegistrationAuditLogService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogServiceUtil} to access the amf registration audit log remote service.
	 */

	/**
	 * Returns the amf registration local service.
	 *
	 * @return the amf registration local service
	 */
	public com.liferay.docs.amf.registration.sb.service.AmfRegistrationLocalService getAmfRegistrationLocalService() {
		return amfRegistrationLocalService;
	}

	/**
	 * Sets the amf registration local service.
	 *
	 * @param amfRegistrationLocalService the amf registration local service
	 */
	public void setAmfRegistrationLocalService(
		com.liferay.docs.amf.registration.sb.service.AmfRegistrationLocalService amfRegistrationLocalService) {
		this.amfRegistrationLocalService = amfRegistrationLocalService;
	}

	/**
	 * Returns the amf registration remote service.
	 *
	 * @return the amf registration remote service
	 */
	public com.liferay.docs.amf.registration.sb.service.AmfRegistrationService getAmfRegistrationService() {
		return amfRegistrationService;
	}

	/**
	 * Sets the amf registration remote service.
	 *
	 * @param amfRegistrationService the amf registration remote service
	 */
	public void setAmfRegistrationService(
		com.liferay.docs.amf.registration.sb.service.AmfRegistrationService amfRegistrationService) {
		this.amfRegistrationService = amfRegistrationService;
	}

	/**
	 * Returns the amf registration persistence.
	 *
	 * @return the amf registration persistence
	 */
	public AmfRegistrationPersistence getAmfRegistrationPersistence() {
		return amfRegistrationPersistence;
	}

	/**
	 * Sets the amf registration persistence.
	 *
	 * @param amfRegistrationPersistence the amf registration persistence
	 */
	public void setAmfRegistrationPersistence(
		AmfRegistrationPersistence amfRegistrationPersistence) {
		this.amfRegistrationPersistence = amfRegistrationPersistence;
	}

	/**
	 * Returns the amf registration finder.
	 *
	 * @return the amf registration finder
	 */
	public AmfRegistrationFinder getAmfRegistrationFinder() {
		return amfRegistrationFinder;
	}

	/**
	 * Sets the amf registration finder.
	 *
	 * @param amfRegistrationFinder the amf registration finder
	 */
	public void setAmfRegistrationFinder(
		AmfRegistrationFinder amfRegistrationFinder) {
		this.amfRegistrationFinder = amfRegistrationFinder;
	}

	/**
	 * Returns the amf registration audit log local service.
	 *
	 * @return the amf registration audit log local service
	 */
	public com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogLocalService getAmfRegistrationAuditLogLocalService() {
		return amfRegistrationAuditLogLocalService;
	}

	/**
	 * Sets the amf registration audit log local service.
	 *
	 * @param amfRegistrationAuditLogLocalService the amf registration audit log local service
	 */
	public void setAmfRegistrationAuditLogLocalService(
		com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogLocalService amfRegistrationAuditLogLocalService) {
		this.amfRegistrationAuditLogLocalService = amfRegistrationAuditLogLocalService;
	}

	/**
	 * Returns the amf registration audit log remote service.
	 *
	 * @return the amf registration audit log remote service
	 */
	public AmfRegistrationAuditLogService getAmfRegistrationAuditLogService() {
		return amfRegistrationAuditLogService;
	}

	/**
	 * Sets the amf registration audit log remote service.
	 *
	 * @param amfRegistrationAuditLogService the amf registration audit log remote service
	 */
	public void setAmfRegistrationAuditLogService(
		AmfRegistrationAuditLogService amfRegistrationAuditLogService) {
		this.amfRegistrationAuditLogService = amfRegistrationAuditLogService;
	}

	/**
	 * Returns the amf registration audit log persistence.
	 *
	 * @return the amf registration audit log persistence
	 */
	public AmfRegistrationAuditLogPersistence getAmfRegistrationAuditLogPersistence() {
		return amfRegistrationAuditLogPersistence;
	}

	/**
	 * Sets the amf registration audit log persistence.
	 *
	 * @param amfRegistrationAuditLogPersistence the amf registration audit log persistence
	 */
	public void setAmfRegistrationAuditLogPersistence(
		AmfRegistrationAuditLogPersistence amfRegistrationAuditLogPersistence) {
		this.amfRegistrationAuditLogPersistence = amfRegistrationAuditLogPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AmfRegistrationAuditLogService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AmfRegistrationAuditLog.class;
	}

	protected String getModelClassName() {
		return AmfRegistrationAuditLog.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = amfRegistrationAuditLogPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.docs.amf.registration.sb.service.AmfRegistrationLocalService.class)
	protected com.liferay.docs.amf.registration.sb.service.AmfRegistrationLocalService amfRegistrationLocalService;
	@BeanReference(type = com.liferay.docs.amf.registration.sb.service.AmfRegistrationService.class)
	protected com.liferay.docs.amf.registration.sb.service.AmfRegistrationService amfRegistrationService;
	@BeanReference(type = AmfRegistrationPersistence.class)
	protected AmfRegistrationPersistence amfRegistrationPersistence;
	@BeanReference(type = AmfRegistrationFinder.class)
	protected AmfRegistrationFinder amfRegistrationFinder;
	@BeanReference(type = com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogLocalService.class)
	protected com.liferay.docs.amf.registration.sb.service.AmfRegistrationAuditLogLocalService amfRegistrationAuditLogLocalService;
	@BeanReference(type = AmfRegistrationAuditLogService.class)
	protected AmfRegistrationAuditLogService amfRegistrationAuditLogService;
	@BeanReference(type = AmfRegistrationAuditLogPersistence.class)
	protected AmfRegistrationAuditLogPersistence amfRegistrationAuditLogPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}